# Устанавливаем ноль, чтобы автоматически присваивался порт
server:
  port: 0

# id сервера eureka, приложения, где будет запускаться
spring:
  application:
    name: "push-notification-service"

# куда будет проходить регистрация микросервисов
eureka:
  client:
    service-url:
      defaultZone: "http://localhost:8761/eureka"



